### ISSUE TITLE
Site ownership

### ISSUE THREAD

**Issue by wayneashleyberry** [we-are-next/www.larasites.com#36]
- Sites can be submitted by many people, but are only owned or authored by one person.
- We'll need a way to manually add users before we can do this, in case the owner hasn't used the site yet.
- The owner should always be the company's official twitter account where possible.
- Sites won't always have an owner.

**Comment by shawnroos** [comment]
@wayneashleyberry :heavy_check_mark:

**Comment by wayneashleyberry** [comment]
Closed in https://github.com/we-are-next/www.larasites.com/issues/45 and deployed to production.

![screen shot 2015-08-31 at 3 17 20 pm](https://cloud.githubusercontent.com/assets/727262/9579504/6d5e6ef0-4ff3-11e5-930f-05165d321ee1.png)
