### ISSUE TITLE
[FEATURE] Add site seeder

### ISSUE THREAD

**Issue by assertchris** [we-are-next/www.larasites.com#41]
It might be useful to new contributors if there were seeders to compliment the migrations. That way folks can start hacking on site structure without needing to set Twitter/Cloudinary/Sentry up...
 
Keen to PR if you think it's a good idea.

**Comment by wayneashleyberry** [comment]
Great idea :)

**Comment by wayneashleyberry** [comment]
https://github.com/we-are-next/www.larasites.com/pull/43
